### ISSUE TITLE
Error: Bad Hex with basic configuration

### ISSUE THREAD

**Issue by redoper1** [balgamat/biograf#1]
Hello Matěj,

I just tried to include this player in just created react-app (via `yarn create react-app`) and after using your provided basic controls configuration from Readme Get Started section into my App component I've got the "Bad Hex" error.

It looks like there is some problem with hex color syntax in your Volume bar component on line 37 according to the error screen, but I didn't found any problem yet.

```
hex2rgba
PROJECT_PATH/node_modules/biograf/utils/hex2rgba.js:18
(anonymous function)
PROJECT_PATH/node_modules/biograf/VideoPlayer/Controls/Volume/VolumeBar.js:37
```

But it can be a problem only on my side, but I don't see any opportunity to make some mistake here.

**Comment by balgamat** [comment]
Hi @redoper1 ,

sorry for the wait... First and foremost: thanks a bunch for the valuable feedback! There was indeed missing fallback value for VolumeBar but all should be fine now 👍
